/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Node.js binding for LocalIndex */
export declare class LocalIndex {
  constructor(folderPath: string, indexName?: string | undefined | null)
  createIndex(config?: string | undefined | null): Promise<void>
  isIndexCreated(): Promise<boolean>
  insertItem(itemJson: string): Promise<string>
  getItem(id: string): Promise<string | null>
  queryItems(vector: Array<number>, topK?: number | undefined | null, filter?: string | undefined | null): Promise<string>
  deleteItem(id: string): Promise<void>
  listItems(options?: string | undefined | null): Promise<string>
  beginUpdate(): Promise<void>
  endUpdate(): Promise<void>
  cancelUpdate(): Promise<void>
  deleteIndex(): Promise<void>
}
